#!/bin/bash
#
# ./composer - Acesso ao composer dockerizado 
#
# Este programa executa comandos do composer que está localizado dentro do conteiner
# docker, dispensando a necessidade de instalar o composer no computador local

PHP_CONTAINER='iquety-app'

docker-compose up -d

if [ "$1" == "analyse" ] || [ "$1" == "lint" ]; then
    docker run \
        -e RUN_LOCAL=true \
        -e VALIDATE_MARKDOWN=true \
        -e MARKDOWN_CONFIG_FILE="docs/.lint.yml" \
        -e FILTER_REGEX_INCLUDE="/docs/.*" \
        -v "$(pwd)/docs/.lint.yml":"/action/lib/.automation/docs/.lint.yml" \
        -v "$(pwd)":"/tmp/lint" github/super-linter
fi

if [ "$1" == "lint" ]; then
    exit;
fi 

if [ "$1" == "bash" ]; then
    docker exec -it $PHP_CONTAINER bash

    exit 0
fi

docker exec -it $PHP_CONTAINER \
    composer $@
